<?php
namespace Tests\Feature;
use App\Models\Alumno; use App\Models\RecorridoTransporte; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class TransporteTest extends TestCase { use RefreshDatabase;
 public function test_transport_accepts_at_most_four_routes(): void { $this->actingAs(User::factory()->create(['role'=>'admin'])); for($n=1;$n<=4;$n++) $this->post(route('admin.transporte.recorridos.store'),['nombre'=>"Recorrido $n",'zona'=>"Zona $n",'cupo'=>20])->assertRedirect(route('admin.transporte.index')); $this->post(route('admin.transporte.recorridos.store'),['nombre'=>'Recorrido 5','zona'=>'Zona 5','cupo'=>20])->assertSessionHasErrors('nombre'); $this->assertDatabaseCount('recorridos_transporte',4); }
 public function test_student_cannot_have_more_than_one_transport_enrollment(): void { $this->actingAs(User::factory()->create(['role'=>'admin'])); $alumno=$this->alumno('001'); $uno=$this->recorrido('Norte'); $dos=$this->recorrido('Sur'); $this->post(route('admin.transporte.inscripciones.store'),['alumno_id'=>$alumno->id,'recorrido_transporte_id'=>$uno->id])->assertRedirect(route('admin.transporte.index')); $this->post(route('admin.transporte.inscripciones.store'),['alumno_id'=>$alumno->id,'recorrido_transporte_id'=>$dos->id])->assertSessionHasErrors('alumno_id'); }
 public function test_route_cannot_exceed_capacity(): void { $this->actingAs(User::factory()->create(['role'=>'admin'])); $recorrido=$this->recorrido('Norte',1); $this->post(route('admin.transporte.inscripciones.store'),['alumno_id'=>$this->alumno('001')->id,'recorrido_transporte_id'=>$recorrido->id]); $this->post(route('admin.transporte.inscripciones.store'),['alumno_id'=>$this->alumno('002')->id,'recorrido_transporte_id'=>$recorrido->id])->assertSessionHasErrors('recorrido_transporte_id'); }
 private function recorrido(string $nombre,int $cupo=20): RecorridoTransporte { return RecorridoTransporte::create(['nombre'=>"Recorrido $nombre",'zona'=>"Zona $nombre",'cupo'=>$cupo]); } private function alumno(string $id): Alumno { return Alumno::create(['legajo'=>"T-$id",'dni'=>"430000$id",'nombre'=>'Alumno','apellido'=>"Transporte $id",'fecha_nacimiento'=>'2012-01-10','domicilio'=>'Calle 1']); }
}
