<?php
namespace App\Http\Controllers;
use App\Models\Alumno; use App\Models\InscripcionTransporte; use App\Models\RecorridoTransporte; use Illuminate\Http\Request; use Illuminate\Validation\ValidationException;
class TransporteController extends Controller {
 public function index(){ return view('transporte.index',['recorridos'=>RecorridoTransporte::withCount(['inscripciones as inscriptos'=>fn($q)=>$q->where('activo',true)])->orderBy('nombre')->get(),'inscripciones'=>InscripcionTransporte::with(['alumno','recorrido'])->where('activo',true)->get(),'alumnos'=>Alumno::where('activo',true)->orderBy('apellido')->get()]); }
 public function storeRecorrido(Request $request){ if(RecorridoTransporte::count() >= 4) throw ValidationException::withMessages(['nombre'=>'El servicio de transporte admite un máximo de cuatro recorridos.']); $datos=$request->validate(['nombre'=>'required|string|max:100|unique:recorridos_transporte,nombre','zona'=>'required|string|max:150','cupo'=>'required|integer|min:1|max:1000']); RecorridoTransporte::create($datos); return redirect()->route('admin.transporte.index')->with('success','Recorrido de transporte registrado correctamente.'); }
 public function storeInscripcion(Request $request){ $datos=$request->validate(['alumno_id'=>'required|exists:alumnos,id','recorrido_transporte_id'=>'required|exists:recorridos_transporte,id']); if(InscripcionTransporte::where('alumno_id',$datos['alumno_id'])->exists()) throw ValidationException::withMessages(['alumno_id'=>'El alumno ya posee una inscripción de transporte.']); $recorrido=RecorridoTransporte::findOrFail($datos['recorrido_transporte_id']); if(!$recorrido->activo || $recorrido->inscripciones()->where('activo',true)->count() >= $recorrido->cupo) throw ValidationException::withMessages(['recorrido_transporte_id'=>'El recorrido seleccionado no tiene cupos disponibles.']); InscripcionTransporte::create($datos); return redirect()->route('admin.transporte.index')->with('success','Alumno inscripto al transporte correctamente.'); }
 public function destroyInscripcion(InscripcionTransporte $inscripcionTransporte){ $inscripcionTransporte->update(['activo'=>false]); return redirect()->route('admin.transporte.index')->with('success','Inscripción de transporte dada de baja.'); }
}
